### ISSUE TITLE
TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by fwatermann** [SmartCity-2022/Service-Buergerbuero#33]
Stacktrace:
```
/app/middlewares/auth.js:17
console.log(`auth recived cookies: ${cookies}`);
^
TypeError: Cannot convert object to primitive value
at auth (/app/middlewares/auth.js:17:42)
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
at next (/app/node_modules/express/lib/router/route.js:144:13)
at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
at /app/node_modules/express/lib/router/index.js:286:22
at Function.process_params (/app/node_modules/express/lib/router/index.js:348:12)
at next (/app/node_modules/express/lib/router/index.js:280:10)
at Function.handle (/app/node_modules/express/lib/router/index.js:175:3)
at router (/app/node_modules/express/lib/router/index.js:47:12)
at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)
at /app/node_modules/express/lib/router/index.js:289:7
at Function.process_params (/app/node_modules/express/lib/router/index.js:348:12)
at next (/app/node_modules/express/lib/router/index.js:280:10)
at cors (/app/node_modules/cors/lib/index.js:188:7)
```

**Comment by shakerrrr** [comment]
https://github.com/SmartCity-2022/Service-Buergerbuero/pull/32/commits/21f5e37b3195ba1727d283feca13f20dfa75160d

**Comment by Flamtky** [comment]
@shakerrrr Bitte Issues nicht einfach schließen, wenn überhauppt im Commit `closes #33` schreiben. Es gibt auch andere Keywörter: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue. Sonst einfach auch im PR hinterlegen diese Issues werden dann automatisch geschlossen wenn der PR in den default geht.
